DROP DATABASE Quanlysinhvien

CREATE DATABASE Quanlysinhvien

USE Quanlysinhvien

CREATE TABLE KHOA(
	MAKHOA char(4),
	TENKHOA varchar(20),
	
	PRIMARY KEY(MAKHOA)
)

CREATE TABLE MONHOC(
	TENMH varchar(20),
	MAMH varchar(4),
	SOTIET tinyint,
	
	PRIMARY KEY(MAMH)
)

CREATE TABLE SINHVIEN(
	HOSV varchar(15),
	TENSV varchar(4),
	MASV char(4),
	NGAYSINH date,
	PHAI varchar(3),
	MAKHOA char(4),
	
	PRIMARY KEY(MASV),
	CONSTRAINT FK_SINHVIEN_MAKHOA_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE KETQUA(
	MASV char(4),
	MAMH varchar(4),
	LANTHI tinyint,
	DIEM tinyint,
	
	PRIMARY KEY(MASV,MAMH,LANTHI),
	CONSTRAINT FK_KETQUA_MASV_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_KETQUA_MAMH_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH) ON UPDATE CASCADE ON DELETE CASCADE
)

--Q2
ALTER TABLE KETQUA DROP CONSTRAINT FK_KETQUA_MASV_SINHVIEN
ALTER TABLE KETQUA DROP CONSTRAINT FK_KETQUA_MAMH_MONHOC

--Q3
ALTER TABLE SINHVIEN DROP CONSTRAINT FK_SINHVIEN_MAKHOA_KHOA
DROP TABLE KHOA
DROP TABLE MONHOC

--Q4
CREATE TABLE KHOA(
	MAKHOA char(4),
	TENKHOA varchar(20),
	PRIMARY KEY(MAKHOA)
)

CREATE TABLE MONHOC(
	TENMH varchar(20),
	MAMH varchar(4),
	SOTIET tinyint,
	PRIMARY KEY(MAMH)
)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_MAKHOA_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE KETQUA ADD CONSTRAINT FK_KETQUA_MAMH_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE KETQUA ADD CONSTRAINT FK_KETQUA_MASV_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV) ON UPDATE CASCADE ON DELETE CASCADE

--Q5
--MONHOC
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Anh Van', 'AV', 45)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Co So Du Lieu', 'CSDL', 45)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Ky Thuat Lap Trinh', 'KTLT', 60)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Ke Toan Tai Chinh', 'KTTC', 45)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Toan Cao Cap', 'TCC', 60)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Tin Hoc Van Phong', 'THVP', 30)
INSERT INTO MONHOC(TENMH,MAMH,SOTIET) VALUES('Tri Tue Nhan Tao', 'TTNT', 45)

--KHOA
INSERT INTO KHOA(MAKHOA,TENKHOA) VALUES('AVAN','Khoa anh Van')
INSERT INTO KHOA(MAKHOA,TENKHOA) VALUES('CNTT','Cong Nghe Thong Tin')
INSERT INTO KHOA(MAKHOA,TENKHOA) VALUES('DTVT','Dien Tu Vien Thong')
INSERT INTO KHOA(MAKHOA,TENKHOA) VALUES('QTKD','Quan Tri Kinh Doanh')

--SINHVIEN
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Tran Minh', 'Son', 'S001', CONVERT(date,'05/01/1985',101),'Nam','CNTT')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Nguyen Quoc', 'Bao', 'S002', CONVERT(date,'06/15/1986',101), 'Nam', 'CNTT')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Phan Anh', 'Tung', 'S003', CONVERT(date,'12/20/1983',101), 'Nam', 'QTKD')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Bui Thi anh', 'Thu', 'S004', CONVERT(date,'02/01/1985',101), 'Nu', 'QTKD')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Le Thi Lan', 'Anh', 'S005', CONVERT(date,'07/03/1987',101), 'Nu', 'DTVT')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Nguyen Thi', 'Lam', 'S006', CONVERT(date,'11/25/1984',101), 'Nu', 'DTVT')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Phan Thi', 'Ha', 'S007', CONVERT(date,'07/03/1988',101), 'Nu', 'CNTT')
INSERT INTO SINHVIEN(HOSV,TENSV,MASV,NGAYSINH,PHAI,MAKHOA) VALUES('Tran The', 'Dung', 'S008', CONVERT(date,'01/21/1985',101), 'Nam', 'CNTT')

--KETQUA
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S001','CSDL',1,4)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S001','TCC',1,6)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S002','CSDL',1,3)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S002','CSDL',2,6)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S003','KTTC',1,5)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S004','AV',1,8)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S004','THVP',1,4)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S004','THVP',2,8)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S006','TCC',1,5)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S007','AV',1,2)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S007','AV',2,9)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S007','KTLT',1,6)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S008','AV',1,7)

--Q6
UPDATE MONHOC SET SOTIET = 30 WHERE TENMH = 'Tri Tue Nhan Tao'
--SELECT * FROM MONHOC
--Q7
--SELECT * FROM KETQUA
DELETE KETQUA WHERE MASV = 'S001'

--Q8
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S001', 'CSDL',1,4)
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEM) VALUES('S001', 'TCC',1,6)

--Q9
--SELECT * FROM SINHVIEN
UPDATE SINHVIEN
SET HOSV = 'Nguyen Van', Phai = 'Nam'
WHERE HOSV = 'Nguyen Thi' and TENSV = 'Lam'

--Q10
UPDATE SINHVIEN
SET MAKHOA = 'CNTT'
WHERE HOSV = 'Le Thi Lan' AND TENSV = 'Anh'

--CHECK
SELECT * FROM SINHVIEN
SELECT * FROM KHOA
SELECT * FROM MONHOC
SELECT * FROM KETQUA
---------------------------------------------
